version: '3'
services:
  mariadb:
     build: ./requirements/mariadb
     container_name: mariadb
     ports:
      - "3306"
     networks:
      - db
     restart: unless-stopped 
     volumes:
        - /home/aait-ham/data/mysql:/var/lib/mysql    
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "9000"
    # depends_on:
    #   - mariadb
    networks:
      - inception
      - db
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
     - "443:443"
    restart: unless-stopped
    depends_on:
     - wordpress
    networks:
      - inception

networks:
  inception:
  db: